# Generated by Django 3.2.6 on 2021-08-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='CN',
            field=models.CharField(choices=[('', None), ('MILK', 'MILK'), ('SIZE', 'SIZE'), ('SHOTS', 'SHOTS'), ('KIND', 'KIND')], max_length=6, null=True),
        ),
    ]
